services:
  supcountbe.api:
    container_name: supcountbe.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=supcountdb;DataBase=SupCountDb;Persist Security Info=True;User ID=sa;Password=kalilinux2.0@@;Trust Server Certificate=True;MultipleActiveResultSets=true;
      - JWT__Key=f1cQ1bgc8lY7UIHdaIZRTJE29AwiE5eAg5XTR3e1a4eDZlMhld1THVbb18uzdeAW
      - JWT__ExpirationInMinutes=20
      - JWT__Issuer=SupCountApi
      - JWT__Audience=SupCountApiUser
    ports:
      - "8081:8080"
    depends_on:
      - supcountdb
    networks:
      - supcount-network
    
  supcountdb:
     container_name: subcountdb
     image: mcr.microsoft.com/mssql/server:latest
     environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "kalilinux2.0@@"
       MMSQL_PID : Express
     ports:
       - "1433:1433"
     networks:
       - supcount-network
     volumes:
       - supcount-db-data:/var/opt/mssql

networks:
  supcount-network:     
  
volumes:
  supcount-db-data: